import Head from "next/head";
import List from "../components/List/List";
import Form from "../components/Form/Form";
import Header from "../components/Header/Header";
import styles from "@/styles/Home.module.css";

export default function Home() {
  return (
    <>
      <Head>
        <title>Servers</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <Header/>
      <main className={styles.main}>
        <div className={styles.container}>
          <List />
          <section>
            <h1 className="font-bold text-2xl mb-2">Edit Form</h1>
            <Form />
          </section>
        </div>
      </main>
    </>
  );
}
